### ISSUE TITLE
Error connecting to controller with http api

### ISSUE THREAD

**Issue by Beeso27** [jayyzhao/homebridge-neo-smart-blinds#1]
**Describe Your Problem:**
If I try to configure the plugin to use the http api it seems like it is still trying to connect to the controller on port 443 ? and the connection is refused. (see below)

When I set to use TCP then a command is sent but nothing happens to the blinds. (see command sent from logs)

Have I set something up incorrectly here? 

**Logs:**

[25/06/2024, 17:17:27] [NeoSmartBlinds] Loading accessory from cache: Master 1
[25/06/2024, 17:17:27] Homebridge v1.8.3 (HAP v0.12.2) (NeoSmartBlinds) is running on port 44026.
Error: connect ECONNREFUSED 192.168.1.9:443
    at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:519:28)
    at ClientRequest.eventHandlers.<computed> (/var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NeoSmartBlindsPlatform.login (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/src/platform.ts:142:22)
    at NeoSmartBlindsPlatform.discoverDevices (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/src/platform.ts:69:7)
[25/06/2024, 17:17:27] [NeoSmartBlinds] Child bridge process ended
[25/06/2024, 17:17:27] [NeoSmartBlinds] Process Ended. Code: 1, Signal: null
[25/06/2024, 17:17:34] [NeoSmartBlinds] Restarting Process...
[25/06/2024, 17:17:35] [NeoSmartBlinds] Launched child bridge with PID 47208
[25/06/2024, 17:17:35] Registering platform 'homebridge-neo-smartblinds.NeoSmartBlinds'
[25/06/2024, 17:17:35] [NeoSmartBlinds] Loaded homebridge-neo-smartblinds v1.0.12 child bridge successfully
[25/06/2024, 17:17:35] Loaded 1 cached accessories from cachedAccessories.0E96B1B1502D.
[25/06/2024, 17:17:35] [NeoSmartBlinds] Loading accessory from cache: Master 1
[25/06/2024, 17:17:35] Homebridge v1.8.3 (HAP v0.12.2) (NeoSmartBlinds) is running on port 44026.
Error: connect ECONNREFUSED 192.168.1.9:443
    at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:519:28)
    at ClientRequest.eventHandlers.<computed> (/var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NeoSmartBlindsPlatform.login (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/src/platform.ts:142:22)
    at NeoSmartBlindsPlatform.discoverDevices (file:///var/lib/homebridge/node_modules/homebridge-neo-smartblinds/src/platform.ts:69:7)
[25/06/2024, 17:17:35] [NeoSmartBlinds] Child bridge process ended
[25/06/2024, 17:17:35] [NeoSmartBlinds] Process Ended. Code: 1, Signal: null

```
[25/06/2024, 17:25:29] [NeoSmartBlinds] Master 1 is Opening
[25/06/2024, 17:25:29] [NeoSmartBlinds] {"4zt_qSjZWSmwDMgVtvgGiw,esp32,us-east-1":[{"hash":"0528931","command":"up","channel":"01","token":"055.032","motor":"wt"}]}

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by jayyzhao** [comment]
this plugin is an adaptation to use the http api  - the same one that the application it self uses. If you want to use the local api , suggest you use the other similar plugins there.

**Comment by Beeso27** [comment]
Thanks for the reply! When I try to use the http api to connect to the controller it tries to connect via port 443 (usually reserved for https) and the connection is refused. Have I not set something up correctly on the smart controller? I can't see anyway to connect to the controller directly only via the app?
